models:
  # base model used for quick CPU testing
  # ~2000 lines / batch size != hugging iterations ?
  - name: distilbert-base-uncased-finetuned-sst-2-english
    nickname: baby_bert_1
    type: transformer
    lr: 2e-5
    epochs: 1
    batch_size: 32
    dropout: 0.1
    max_len: 128

  # - name: distilbert-base-uncased-finetuned-sst-2-english
  #   nickname: baby_bert_2
  #   type: transformer
  #   lr: 2e-5
  #   epochs: 1
  #   batch_size: 32
  #   dropout: 0.2
  #   max_len: 128

  # - name: SVR_Baseline
  #   type: sklearn
  #   max_features: 5000

  # - name: bert-base-multilingual-cased
  #   type: transformer
  #   lr: 1e-5
  #   epochs: 8
  #   batch_size: 32
  #   dropout: 0.1

  # - name: microsoft/deberta-v3-base
  #   type: transformer
  #   lr: 1e-5
  #   epochs: 8
  #   batch_size: 32
  #   dropout: 0.1

  # - name: roberta-base
  #   type: transformer
  #   lr: 1e-6
  #   epochs: 8
  #   batch_size: 32
  #   dropout: 0.1
  