#!/usr/bin/env python3
"""Run DimABSA contextual augmentation for multiple retry settings."""

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
# Script d'augmentation contextual utilise pour chaque valeur de retries.
AUG_SCRIPT = REPO_ROOT / "scripts" / "augment_dimabsa_contextual.py"

INPUT_FILE = Path(
    "~/DimABSA2026-main/task-dataset/track_a/subtask_1/eng/"
    "eng_laptop_train_alltasks.jsonl"
)
OUTPUT_DIR = Path(
    "~/DimABSA2026-main/task-dataset/track_a/subtask_1/eng/"
    "contextual_aug_retry_sweep"
)

RETRIES = [5, 10, 20]
# Parametres communs a toutes les executions du sweep.
PARAMS = {
    "num_aug": 1,
    "model_path": "distilbert-base-uncased",
    "batch_size": 1,
    "aug_p": 0.15,
    "aug_max": 2,
    "top_k": 100,
    "aug_min": 1,
    "seed": 42,
    "action": "substitute",
}


def count_lines(path):
    # Compte le nombre d'enregistrements JSONL (1 ligne = 1 record).
    with path.open(encoding="utf-8") as f:
        return sum(1 for _ in f)


def concatenate(original_path, augmented_path, combined_path):
    # Concatene original + augmente pour produire un fichier final unique.
    with combined_path.open("w", encoding="utf-8") as out:
        for source in (original_path, augmented_path):
            with source.open(encoding="utf-8") as src:
                for line in src:
                    out.write(line)


def run_generation(python_exe, retries):
    # Nomme les sorties en fonction de la valeur de retries testee.
    augmented_only = OUTPUT_DIR / f"eng_laptop_train_alltasks_contextual_aug_retry{retries}_augmented_only.jsonl"
    original_plus_augmented = (
        OUTPUT_DIR / f"eng_laptop_train_alltasks_contextual_aug_retry{retries}_original_plus_augmented.jsonl"
    )

    cmd = [
        python_exe,
        str(AUG_SCRIPT),
        str(INPUT_FILE),
        str(augmented_only),
        "--num-aug",
        str(PARAMS["num_aug"]),
        "--model-path",
        PARAMS["model_path"],
        "--batch-size",
        str(PARAMS["batch_size"]),
        "--aug-p",
        str(PARAMS["aug_p"]),
        "--aug-max",
        str(PARAMS["aug_max"]),
        "--top-k",
        str(PARAMS["top_k"]),
        "--aug-min",
        str(PARAMS["aug_min"]),
        "--seed",
        str(PARAMS["seed"]),
        "--action",
        PARAMS["action"],
        "--retries",
        str(retries),
        "--no-original",
    ]

    # Lance le script d'augmentation dans la racine du repository.
    print("Running:", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, cwd=REPO_ROOT)

    # Recompose un dataset final: original suivi des exemples augmentes.
    concatenate(INPUT_FILE, augmented_only, original_plus_augmented)

    return {
        "retries": retries,
        "augmented_only_file": str(augmented_only),
        "augmented_only_records": count_lines(augmented_only),
        "original_plus_augmented_file": str(original_plus_augmented),
        "original_plus_augmented_records": count_lines(original_plus_augmented),
    }


def write_params_log(results):
    # Sauvegarde un recap complet des parametres et sorties du sweep.
    log_path = OUTPUT_DIR / "augmentation_params.txt"
    payload = {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "input_file": str(INPUT_FILE),
        "input_records": count_lines(INPUT_FILE),
        "output_dir": str(OUTPUT_DIR),
        "python": sys.executable,
        "augmentation_script": str(AUG_SCRIPT),
        "params": PARAMS,
        "retry_settings": RETRIES,
        "outputs": results,
        "notes": [
            "For each retry value, the augmented_only file is generated by the augmenter.",
            "For each retry value, the original_plus_augmented file is original JSONL concatenated with augmented_only JSONL.",
            "The script protects non-NULL Aspect and Opinion phrases and rejects candidates where those phrases disappear.",
        ],
    }
    with log_path.open("w", encoding="utf-8") as f:
        f.write(json.dumps(payload, indent=2, ensure_ascii=False))
        f.write("\n")
    return log_path


def main():
    # Prepare le dossier de sortie puis execute toutes les variantes de retries.
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    python_exe = sys.executable

    results = []
    for retries in RETRIES:
        results.append(run_generation(python_exe, retries))

    # Ecrit un journal de trace pour reproduire exactement les essais.
    log_path = write_params_log(results)
    print(f"Wrote parameter log to {log_path}")


if __name__ == "__main__":
    main()
